import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/sonner";
import { QueryProvider } from "@/components/query-provider";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Load Zapier chatbot script globally */}
        <script
          async
          type="module"
          src="https://interfaces.zapier.com/assets/web-components/zapier-interfaces/zapier-interfaces.esm.js"
        />
      </head>
      <body className={cn(inter.className, "antialiased min-h-screen")}>
        <QueryProvider>
          <Toaster />
          {children}

          {/* Zapier Chatbot Embed (popup bottom-right) */}
          <div
            dangerouslySetInnerHTML={{
              __html: `
                <zapier-interfaces-chatbot-embed
                  is-popup="true"
                  chatbot-id="cmezezd3p003pmonduxsfx5i2"
                ></zapier-interfaces-chatbot-embed>
              `,
            }}
          />
        </QueryProvider>
      </body>
    </html>
  );
}
